import '../styles/globals.scss';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  preload: true,
  fallback: ['Helvatica', 'Verdana'],
  adjustFontFallback: true,
  subsets: ['latin'],
});

export const metadata = {
  title: 'Home | Sajad Shafi',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
