import { ThemeProvider } from '@/store/ThemeContext';
import '../styles/globals.scss';
import Navbar from '@/components/Navbar/Navbar';

export const metadata = {
  title: 'Home | Sajad Shafi',
  description: 'Generated by create next app',
  icons: {
    icon: {
      url: '/favicon.png',
      type: 'image/png',
    },
  },
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <ThemeProvider>
        <Navbar />
        <main>{children}</main>
      </ThemeProvider>
    </html>
  );
};

export default RootLayout;
