import { ThemeProvider } from '@/store/ThemeContext';
import '../styles/globals.scss';
import Navbar from '@/components/Navbar/Navbar';
import fonts from '@/utils/fontConfig';

export const metadata = {
  title: 'Home | Sajad Shafi',
  description: 'Generated by create next app',
  icons: {
    icon: {
      url: '/favicon.png',
      type: 'image/png',
    },
  },
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <ThemeProvider>
        <div
          className={`${fonts.poppins.variable} relative ${fonts.montserrat.variable}`}>
          <Navbar />
          {children}
        </div>
      </ThemeProvider>
    </html>
  );
};

export default RootLayout;
